# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/effi/projects/CG_2015

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/effi/projects/CG_2015

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/effi/projects/CG_2015/CMakeFiles /home/effi/projects/CG_2015/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/effi/projects/CG_2015/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named cg_2015

# Build rule for target.
cg_2015: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cg_2015
.PHONY : cg_2015

# fast build rule for target.
cg_2015/fast:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/build
.PHONY : cg_2015/fast

GraphicsObject.o: GraphicsObject.cpp.o
.PHONY : GraphicsObject.o

# target to build an object file
GraphicsObject.cpp.o:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/GraphicsObject.cpp.o
.PHONY : GraphicsObject.cpp.o

GraphicsObject.i: GraphicsObject.cpp.i
.PHONY : GraphicsObject.i

# target to preprocess a source file
GraphicsObject.cpp.i:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/GraphicsObject.cpp.i
.PHONY : GraphicsObject.cpp.i

GraphicsObject.s: GraphicsObject.cpp.s
.PHONY : GraphicsObject.s

# target to generate assembly for a file
GraphicsObject.cpp.s:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/GraphicsObject.cpp.s
.PHONY : GraphicsObject.cpp.s

InitClass.o: InitClass.cpp.o
.PHONY : InitClass.o

# target to build an object file
InitClass.cpp.o:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/InitClass.cpp.o
.PHONY : InitClass.cpp.o

InitClass.i: InitClass.cpp.i
.PHONY : InitClass.i

# target to preprocess a source file
InitClass.cpp.i:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/InitClass.cpp.i
.PHONY : InitClass.cpp.i

InitClass.s: InitClass.cpp.s
.PHONY : InitClass.s

# target to generate assembly for a file
InitClass.cpp.s:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/InitClass.cpp.s
.PHONY : InitClass.cpp.s

MerryGoRound.o: MerryGoRound.cpp.o
.PHONY : MerryGoRound.o

# target to build an object file
MerryGoRound.cpp.o:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/MerryGoRound.cpp.o
.PHONY : MerryGoRound.cpp.o

MerryGoRound.i: MerryGoRound.cpp.i
.PHONY : MerryGoRound.i

# target to preprocess a source file
MerryGoRound.cpp.i:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/MerryGoRound.cpp.i
.PHONY : MerryGoRound.cpp.i

MerryGoRound.s: MerryGoRound.cpp.s
.PHONY : MerryGoRound.s

# target to generate assembly for a file
MerryGoRound.cpp.s:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/MerryGoRound.cpp.s
.PHONY : MerryGoRound.cpp.s

camera.o: camera.cpp.o
.PHONY : camera.o

# target to build an object file
camera.cpp.o:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/camera.cpp.o
.PHONY : camera.cpp.o

camera.i: camera.cpp.i
.PHONY : camera.i

# target to preprocess a source file
camera.cpp.i:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/camera.cpp.i
.PHONY : camera.cpp.i

camera.s: camera.cpp.s
.PHONY : camera.s

# target to generate assembly for a file
camera.cpp.s:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/camera.cpp.s
.PHONY : camera.cpp.s

objloader.o: objloader.cpp.o
.PHONY : objloader.o

# target to build an object file
objloader.cpp.o:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/objloader.cpp.o
.PHONY : objloader.cpp.o

objloader.i: objloader.cpp.i
.PHONY : objloader.i

# target to preprocess a source file
objloader.cpp.i:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/objloader.cpp.i
.PHONY : objloader.cpp.i

objloader.s: objloader.cpp.s
.PHONY : objloader.s

# target to generate assembly for a file
objloader.cpp.s:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/objloader.cpp.s
.PHONY : objloader.cpp.s

tiny_obj_loader.o: tiny_obj_loader.cpp.o
.PHONY : tiny_obj_loader.o

# target to build an object file
tiny_obj_loader.cpp.o:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/tiny_obj_loader.cpp.o
.PHONY : tiny_obj_loader.cpp.o

tiny_obj_loader.i: tiny_obj_loader.cpp.i
.PHONY : tiny_obj_loader.i

# target to preprocess a source file
tiny_obj_loader.cpp.i:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/tiny_obj_loader.cpp.i
.PHONY : tiny_obj_loader.cpp.i

tiny_obj_loader.s: tiny_obj_loader.cpp.s
.PHONY : tiny_obj_loader.s

# target to generate assembly for a file
tiny_obj_loader.cpp.s:
	$(MAKE) -f CMakeFiles/cg_2015.dir/build.make CMakeFiles/cg_2015.dir/tiny_obj_loader.cpp.s
.PHONY : tiny_obj_loader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... cg_2015"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... GraphicsObject.o"
	@echo "... GraphicsObject.i"
	@echo "... GraphicsObject.s"
	@echo "... InitClass.o"
	@echo "... InitClass.i"
	@echo "... InitClass.s"
	@echo "... MerryGoRound.o"
	@echo "... MerryGoRound.i"
	@echo "... MerryGoRound.s"
	@echo "... camera.o"
	@echo "... camera.i"
	@echo "... camera.s"
	@echo "... objloader.o"
	@echo "... objloader.i"
	@echo "... objloader.s"
	@echo "... tiny_obj_loader.o"
	@echo "... tiny_obj_loader.i"
	@echo "... tiny_obj_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

